"use strict";(self.webpackChunk_trionesdev_antd_react_ext=self.webpackChunk_trionesdev_antd_react_ext||[]).push([[8910],{46754:(function(d,n,t){var o;t.r(n),t.d(n,{demos:function(){return m}});var c=t(55420),i=t.n(c),_=t(98312),l=t.n(_),u=t(96540),e=t(58296),a={};t.r(a),t.d(a,{AppToolbar:function(){return e.lt},AvatarEditor:function(){return e.VS},DrawerForm:function(){return e.c4},EditableDesc:function(){return e.K},ExtCheckbox:function(){return e.rf},ExtDatePicker:function(){return e.QI},ExtFormField:function(){return e.mj},ExtInput:function(){return e.eE},ExtInputNumber:function(){return e.jB},ExtRadio:function(){return e.XA},ExtSelect:function(){return e.qM},ExtSwitch:function(){return e.M$},ExtTreeSelect:function(){return e.me},FetchSelect:function(){return e.LU},FetchTreeSelect:function(){return e.$0},FieldWrapper:function(){return e.cm},FieldsMapping:function(){return e.W1},Fieldset:function(){return e.LB},FormCell:function(){return e.JT},GridTable:function(){return e.dT},ImageUpload:function(){return e.BR},Layout:function(){return e.PE},ModalForm:function(){return e.Kw},PageHeader:function(){return e.zY},PictureUpload:function(){return e.gh},ReactDomUtils:function(){return e.L$},SearchToolbar:function(){return e.kt},SessionStorageUtils:function(){return e.Ng},TableToolbar:function(){return e.e1},VerificationCodeInput:function(){return e.Px},VideoUpload:function(){return e.p0},useCssInJs:function(){return e.hD}});var m={"fieldset-demo-base":{component:u.memo(u.lazy(function(){return t.e(4683).then(t.bind(t,79740))})),asset:{type:"BLOCK",id:"fieldset-demo-base",refAtomIds:["fieldset"],dependencies:{"index.tsx":{type:"FILE",value:t(23781).A},react:{type:"NPM",value:"18.3.1"},"@trionesdev/antd-react-ext":{type:"NPM",value:"6.0.0-beta.11"}},entry:"index.tsx"},routeId:"components/fieldset/index",context:{react:o||(o=t.t(u,2)),"@trionesdev/antd-react-ext":a},renderOpts:{compile:(function(){var f=l()(i()().mark(function p(){var s,x=arguments;return i()().wrap(function(r){for(;;)switch(r.prev=r.next){case 0:return r.next=2,t.e(2306).then(t.bind(t,12306));case 2:return r.abrupt("return",(s=r.sent).default.apply(s,x));case 3:case"end":return r.stop()}},p)}));function E(){return f.apply(this,arguments)}return E})()}}}}),73302:(function(d,n,t){t.r(n);const o=[{value:"\u5BF9\u76F8\u5173\u5143\u7D20\u8FDB\u884C\u5206\u7EC4",paraId:0,tocIndex:0}];t.d(n,["texts",0,o])}),23781:(function(d,n){n.A=`import React from 'react';
import {Fieldset} from '@trionesdev/antd-react-ext';

export default ()=>{
  return <div>
    <Fieldset title="\u57FA\u672C\u4FE1\u606F">
      <div>Fieldset Content</div>
    </Fieldset>
  </div>
}
`})}]);
